### ISSUE TITLE
Update for Go-App V10 please

### ISSUE THREAD

**Issue by suntong** [mlctrez/imgtofactbp#1]
I know that the code hasn't been touched for 3 years, but would it be possible to update it to Go-App V10 please?

As I was trying to do it myself, but realized that it's beyond me after trying. See -- 
https://github.com/maxence-charriere/go-app/issues/973

Thanks.

**Comment by mlctrez** [comment]
@suntong 

I've been waiting for go-app V10 to settle a bit before doing any V9 to V10 changes. I'll probably spin off the clipboard component into its own repository.  

This repository will remain unchanged as it works and is very low usage.

**Comment by suntong** [comment]
Ok. thanks, just that, would you close it when you done spinning off the clipboard component into its own repository instead, so that I got notified for it please?

**Comment by mlctrez** [comment]
@suntong I'll @ mention you on the new repository when it gets created.

**Comment by suntong** [comment]
ok. thx!

**Comment by suntong** [comment]
And hope you find time to update to Go-App V10 of your helpful apps as well, [goapp-mdc](https://github.com/mlctrez/goapp-mdc), [chat](https://github.com/mlctrez/chat), etc. thx!
